### ISSUE TITLE
Sending an email address with @ but no . gets a completely different error

### ISSUE THREAD

**Issue by chani3** [steamclock/internetmap#293]
fig@pig.c  is considered a valid email address.
figpig is considered an invalid address in the expected format.
fig@pig is an invalid email address in a completely different error format.

The error string is  'Internal Server Error'  (sorry, AsyncHttpRequest doesn't let me get the error code) and the json is '[{"fields":["Email"],"message":"Email: invalid email address: fig@pig","errorCode":"INVALID_EMAIL_ADDRESS"}]'

the result: android and ios both report a network error (the generic message).

**Comment by apike** [comment]
We're not using an in-app form anymore, so we can close this.
