### ISSUE TITLE
Change globe node selection so camera always points in with south down

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#396]
Once we've made south point down in the typical case in #394, we should improve the orientation for node selection in globe view.

Right now when a node is selected, it naively zooms the camera to be close to the node from the current location. Instead, we should zoom to a point *outside* the globe pointing at the desired node, with south facing down.

**Comment by apike** [comment]
This got closed, it doesn't appear to be done though.

**Comment by jozero** [comment]
@apike Nope, shouldn't of been closed. When you have a chance please check out PR 413. Its the start of an attempt at fixing several of the camera issues.

**Comment by ssawchenko** [comment]
@jozero Putting "Fixes #XXX" in the commit message will automatically close the issue in github.
