### ISSUE TITLE
Integrate Buddybuild SDK for crash reporting

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#414]

**Comment by jozero** [comment]
@apike Turned on for iOS MASTER branch builds in Buddy Build. 

Versions from Master sent via Buddy Build portal now show a splash screen indicating how to send feedback

**Comment by ssawchenko** [comment]
@apike Also turned this on for Android Master branch builds in BB.

This seems like it will always pop up a screen when the user first runs the app - is this what we want? The BB docs make it seem like this feature is more for testers than end users.

**Comment by jotkali** [comment]
I was wondering if that only happens on test builds. I've never seen that pop pop from an app in store.

**Comment by apike** [comment]
The popup should only happen on non-appstore builds. If we see evidence of that happening in production we should definitely treat that as an urgent fix (by configuration or bug report to Buddybuild).

**Comment by ssawchenko** [comment]
Ok cool. This is the first I have seen this feature enabled so that's good to know!
