### ISSUE TITLE
Review README Android instructions

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#419]
There are quite a few old Android tips and instructions from 2013 in the Readme - @ssawchenko can you review these and remove or update any ones that no longer apply?

**Comment by ssawchenko** [comment]
@apike Should I be documenting the datapipeline steps as well? Right now I have a bunch of notes in the readme for the pipeline from when I was trying to put the pieces together, but it is pretty messy.

**Comment by apike** [comment]
That would be nice, but would be a priority 2 IMO - we can fork it into a separate issue if it's time consuming.
