### ISSUE TITLE
Show toolbars in Safari view controllers

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#424]
The standard Safari View Controller has some toolbars so users can share the URL, etc. They're not pretty but they're probably better than doing our own custom X and not being able to (for example) share the URL.

**Comment by apike** [comment]
![image](https://user-images.githubusercontent.com/129240/27938988-a4d087b4-6276-11e7-9e4a-77176a9a701d.png)

**Comment by jotkali** [comment]
@apike This works well for "Managed IT services" and "Open Source" links, but SFSafariViewController does not have a "loadHTMLString" equivalent to show the local to project "credits.html".

Can we put that page up somewhere and point to it ?

**Comment by jotkali** [comment]
the credits.html file : 

[credits.html.zip](https://github.com/steamclock/internetmap/files/1131997/credits.html.zip)

**Comment by apike** [comment]
@jotkali I would say we don't need this for the credits - maybe at one point but there's nowhere to navigate to from it so it's not as important as the web links.
