### ISSUE TITLE
Make Cogeco logo a bit clearer

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#436]
We have the Cogeco logo in the corner of the app since they've funded development of the app. In 1.0 it was more noticeable, but faded down a bit while you were interacting with the map. This seems to have gone away and now it's always very faded - can we bring back the old behaviour?

**Comment by ssawchenko** [comment]
I believe the logo has always faded to 0.3 alpha. Right now it is set to show full brightness for 4 seconds after the backend data is fully loaded, however, we can play around with either making the delay longer OR setting the alpha ~0.5 instead.

**Comment by apike** [comment]
@jotkali Can we make two tweaks to the logo on iOS?

1. Shift it to the right a bit so the bottom margin and right margin are the same
2. Make it un-dim if the map is sitting idle?
