### ISSUE TITLE
Replace "Managed IT Services" menu

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#437]
The folks at Peer 1 would prefer this menu to instead be two menus with specific purposes:
- Contact Cogeco Peer 1
- About Cogeco Peer 1

This is probably better for users and them. We're waiting on specific URLs for these.

**Comment by jotkali** [comment]
iOS version for this updated in branch 437_Replace_About_Menu

**Comment by ssawchenko** [comment]
Updated Info menu (Android) #437

* Managed IT Services replaced with About and Contact pages
* Created AboutPopup
* Added background image to About and Credits popups
Commit:
f77a892c6fe457379ba721a991c01af03be79e23 [f77a892]
Parents:
926c7764f0
Author:
Shayla Sawchenko <shayla.sawchenko@recursecreative.com>
Date:
August 2, 2017 at 3:13:55 PM PDT
