### ISSUE TITLE
iPad timeline and logo misplaced on non-9.7 inch iPads

### ISSUE THREAD

**Issue by rachteo** [steamclock/internetmap#442]
Currently, timeline on iPad seems to be hardcoded for a 9.7-inch iPad.
On a 12.9-inch iPad:
![simulator screen shot jul 27 2017 10 41 01 am](https://user-images.githubusercontent.com/1234900/28684824-a01c0f28-72ba-11e7-8b56-17e9eb570b32.png)

**Comment by jotkali** [comment]
fixed
