### ISSUE TITLE
Make third "i" menu item "Contact Cogeco Peer 1" and open Hubspot form

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#453]
We'll need to style this slightly (@rachteo?) but we now have a Contact Sales form from the Cogeco folks in the form of a JavaScript snippet. We should embed this in the webview and it will create a mobile-friendly form, which should be much nicer than sending people to the desktop website.

```
<html>
<head>
</head>
<body>
<script charset="utf-8" type="text/javascript" src="https://js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
    portalId: '1935908',
    formId: 'efbb8fbc-249b-494a-ac28-8d1192d79a9c'
  });
</script>
</body>
```

**Comment by rachteo** [comment]
What does the form look like at the moment? I can't figure out how to access it...

**Comment by apike** [comment]
For now, to access it you need to paste that HTML into a blank .html file and open it in a browser 😬  It should be in the build fairly soon.

**Comment by rachteo** [comment]
Default form style for reference:
![image](https://user-images.githubusercontent.com/1234900/28948088-505da3e4-7868-11e7-9987-0e8605d570b4.png)

**Comment by ssawchenko** [comment]
Right now my menu order is:
1. Introduction
2. Contact Cogeco Peer 1
3. About Cogeco Peer 1
4. Open Source
5. Credits

@apike When you say "third menu item" do you want us to switch the order of Contact and About?

**Comment by apike** [comment]
@ssawchenko Exactly.

**Comment by rachteo** [comment]
Styled contact form: 
<img src="https://user-images.githubusercontent.com/1234900/28988642-a02d7a4e-7925-11e7-85ae-3cec6030b0d9.png" width="400">
Thoughts?

**Comment by apike** [comment]
That looks good to me except it's not native so the toggle isn't practical - I'll send this over to their Hubspot expert and see if they can style it that way.

**Comment by ssawchenko** [comment]
Android complete and merge to master, assigning to @jotkali for iOS

**Comment by ssawchenko** [comment]
Unless I change the button style on the Android app, the button will look different than the other buttons we have in the app. Right now the app buttons are very rounded. Doubt this is a release blocker though, but something to keep in mind.

**Comment by rachteo** [comment]
Right, forgot about the traceroute buttons! Updated to match those:

<img src="https://user-images.githubusercontent.com/1234900/28990260-904a2130-7930-11e7-9648-39f079832fac.png" width="400">
