### ISSUE TITLE
Make second "i" menu item "About Cogeco Peer 1" with static text

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#459]
Here is the provided text - we can put it in the same style we use for Credits.

## COGECO PEER 1

Cogeco Peer 1 is a wholly-owned subsidiary of Cogeco Communications Inc. (TSX:CCA) and is a global provider of essential business-to-business products and services, such as colocation, network connectivity, hosting, cloud and managed services that allow customers across Canada, Mexico, the United States and Western Europe to focus on their core business. With 16 data centers, extensive FastFiber Network® and more than 50 points of presence in North America and Europe combined, Cogeco Peer 1 is a trusted partner to businesses small, medium and large, providing the ability to access, move, manage and store mission-critical data worldwide, backed by superior customer support.

**Contact Cogeco Peer 1** (Button that goes to the "Contact Cogeco Peer 1" form from #453)

**Comment by ssawchenko** [comment]
@apike Is the button on this page part of the HTML, or a native button? Or did we decide against a button? (I don't see it in the iOS app yet)

**Comment by apike** [comment]
It's probably simpler to do it as a native button.

**Comment by ssawchenko** [comment]
Android complete, assigning to @jotkali for final iOS review
