### ISSUE TITLE
Android first use can call out menus you've tapped

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#472]
On first use, we should have a bool for each menu, and only show you tips for menus you haven't tapped before. Currently you can get this flow:

1. Launch app, new install
2. See popup for search
3. Tap View menu, switch to network view
4. Tap search, tap a result.
5. See popup about View menu even though you've already tapped it

**Comment by apike** [comment]
@ssawchenko We shouldn't hold release for this, but it would be nice to get a fix in the next few days.

**Comment by ssawchenko** [comment]
@apike I thought one of the requirements for the feature was that all tooltips had to be shown at some point? According to the above steps to reproduce, the view tooltip would never be shown.  The above behaviour was by design because of this.

**Comment by apike** [comment]
@ssawchenko All three menus need to be opened - if they open a menu, there's no longer a need to show that particular tooltip. The goal of the feature is to get them to check out all three.

**Comment by ssawchenko** [comment]
@apike Alrighty, my misunderstanding! I will change the functionality to reflect that :)
