### ISSUE TITLE
Visualization centering and tap targets do not work on iPhone Plus

### ISSUE THREAD

**Issue by ssawchenko** [steamclock/internetmap#493]
Issue seen on current app store version - not related to recent changes for iPhoneX support.
Visualization is not correctly centred.

![screen shot 2017-11-09 at 2 47 39 pm](https://user-images.githubusercontent.com/5217641/32633598-f96ec904-c55c-11e7-9436-23b3b898aa74.png)

**Comment by apike** [comment]
How odd - let's get this fixed in the iPhone X update.

**Comment by apike** [comment]
Apparently this was broken for weeks according to @nbrooke - we'll need to prioritize "Plus" testing better in the future.
