### ISSUE TITLE
Fixup remaining iPhoneX UI issues 

### ISSUE THREAD

**Issue by ssawchenko** [steamclock/internetmap#495]
Most issues have been fixed in #484, however, a few UI quirks may remain. 

**Remaining issues:** 
Node details pop over / traceroute: 
![image](https://user-images.githubusercontent.com/5217641/32674568-aafd2980-c608-11e7-95fb-6efac5a89bbf.png)

Waiting for further testing to see if more are found

**Comment by apike** [comment]
@ssawchenko Nigel can pick this up. In a quick test, the only quirk I'm seeing on iPhone X is the bottom padding on that node selection popup - do you know of any others?

**Comment by ssawchenko** [comment]
This was the only one I found, I was waiting for @abey to put my PR through a round of testing to see if he found anything I missed.

**Comment by apike** [comment]
A second issue Abey found on the iPhone X branch - the placement of the "Your Location" spinner doesn't line up with where the corresponding button is now. The size is slightly off, but for now I'm more concerned about placement.

![image](https://user-images.githubusercontent.com/129240/32681958-f8932c6c-c626-11e7-9f84-1e243affca78.png)

**Comment by nbrooke** [comment]
I'm a little unclear on if this is still happening or if it was fixed at some point in the other iPhone X changes. @abey Could you recheck if this most recent problem (misplaced spinner) is still happening, and either close this (if it is fixed now), or if it is still happening, still close this but file another bug just for that.
