### ISSUE TITLE
Node details popup is truncated

### ISSUE THREAD

**Issue by abey** [steamclock/internetmap#499]
### Current Behaviour
If a node is clicked, the popup is truncated so that **Perform Traceroute** button is hidden.

### Expected Behaviour
Popup should not be truncated and Perform Traceroute button should be visible

### Device and App Information
- **Samsung S5** running **Android 5.1.1**
- Build **320** from **master**

### Screenshot
![screenshot_2017-11-14-10-43-31](https://user-images.githubusercontent.com/11465329/32807500-e2837460-c944-11e7-9ebe-970c5cb451fb.png)

**Comment by apike** [comment]
@abey Traceroute is not implemented yet on master on Android, so I think we can close this.
