### ISSUE TITLE
Menu buttons are hard to tap on iPhone X

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#502]
The iPhone X updates work well in general, but there's one odd one - the menu buttons at the top (search, timeline, etc) sometimes just don't activate when I tap them. Tapping between menus, I feel like I need to re-tap like 1/3 of the time. A problem with the 3x assets maybe? Or the tap targets are maybe offset?

**Comment by apike** [comment]
This is still happening - it means that sometimes I try to tap a menu button but tap a node behind it instead in AR mode.

**Comment by nbrooke** [comment]
This should be fixed in master now, might want to have a look on device just to be 100% sure, I only tested in the simulator (thought eh bug was easy to repro there).
