### ISSUE TITLE
Reposition AR mode controls

### ISSUE THREAD

**Issue by nbrooke** [steamclock/internetmap#512]
We need a visual design, some layout selection, and assets for the unique AR UI elements.

The bits we need are:
- A button for toggling AR mode (in the "toolbar"
- An obvious button that appears when you are "placing" the map on a surface
- A more out of the way button that appears when you want to trigger a repositioning of the map once it has already been placed.

![IMG_E1CCA8D53428-1.jpeg](https://images.zenhubusercontent.com/5948628b51aa2c30578226da/a9a3c55b-f7df-4e8b-904c-48dd898ba7b9)

Here's what those look like in the current prototype. Place here button should be big and centre of screen IMO, reposition could be a little more out of the way (doesn't particularly need to be the location it is now).

Note that we also will probably need a look for when we haven't gotten an AR fix yet. That'll always be in placement mode, so we could just have the "place here" button say "Figuring out where you are" and not be tappable, or we could have some separate treatment for that.

**Comment by nbrooke** [comment]
I've added the label for searching for a plane to place things on, and changed it so that the reposition button isn't visible except when you re placed. So right now, here's what the three modes look like:

Initial start, no fix on the ground yet:

![img_f904659d3525-1](https://user-images.githubusercontent.com/275128/36398664-14321f14-157d-11e8-8987-92600bf48799.jpeg)

Placing the map: 

![img_f904659d3525-3](https://user-images.githubusercontent.com/275128/36398681-21d206de-157d-11e8-8455-ba2a6b3f75d5.jpeg)

Map is placed:

![img_f904659d3525-2](https://user-images.githubusercontent.com/275128/36398916-3f799d68-157e-11e8-9003-6e2f9f81e742.jpeg)

**Comment by apike** [comment]
This is definitely an improvement. It seems like a quick iteration would be to put Reposition in the bottom middle, and have it swap for Place Here which would also appear bottom middle, and have Place Here use the button style we use in other places (rounded sides, particular shade of blue)

**Comment by nbrooke** [comment]
Bear in mind that AR doesn't currently lock out the timeline controls, so anything placed at the bottom will either need to either leave room for those, or move up and down as they are enabled/disabled.

It seems to make sense to me to have "Place Here" a little more central / obvious than "Reposition". Reposition is something the you can do if you want and that you probably don't want blocking your view, whereas when you're in placement mode, the button is probably more important than the map itself. There is also the factor that the location you are placing IS actually right in the middle of the screen, so it does make some sense to have the button there. That would be even more obvious if we had some sort of placement reticule or pedestal (see #514), because with that the base of that would appear right above that button.

**Comment by apike** [comment]
Some thoughts on this:

- I wouldn't mind hiding Reposition while in Timeline mode
- Agreed that Place Here should be more obvious - I'd say it should stay as an obvious button, whereas Reposition should stay small and not-highlighted. Maybe bottom-center for Place Here, and bottom left for Reposition?

**Comment by nbrooke** [comment]
@apike Do we want everything to just stay text buttons, or do we want and icons for any of those?

**Comment by apike** [comment]
Reposition maybe should be an icon if we can think of a good one - for this week's seed though text is fine.
