### ISSUE TITLE
More bold highlights in AR mode

### ISSUE THREAD

**Issue by nbrooke** [steamclock/internetmap#515]
The highlight is not super visible in AR, because it's only a subtle colour change. 

I think we should probably have a much more bright highlighted colour in AR (like a fully saturated red or something) and probably increase the size of a selected node as well.

**Comment by nbrooke** [comment]
@apike and/or @rach Any thoughts on what you would like the visual treatment for selected nodes in AR to be?

**Comment by apike** [comment]
There is currently a glowing/bouncing thing right now, but it's blue. What if we made the glow effect bigger, and maybe used the orange instead of blue? Also can we make it render on top of everything instead of being additive?
