### ISSUE TITLE
Hide AR button on unsupported devices

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#530]
Right now it seems to just bring up a black screen on an iPad Air 1.

**Comment by nbrooke** [comment]
The ARConfiguration object (in RootVC.setupSession) has a way to check if we act tally supports AR or not, should just be a matter of disconnecting the last view from the stack view that contains the buttons if AR is unsupported. I believe that iPad Air 1 is a device that would run the app, but not be supported for AR.
