### ISSUE TITLE
Visual style for AR mode controls

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#531]
Forked off of #512 - this splits out the need for some visual polish out of the more urgent need for better positioning of the controls. The current thinking is that we should use a version of the rounded button style for the Place Here button, and a more subtle text-only label for Reposition - maybe in small caps?

**Comment by rachteo** [comment]
Something like this?
<img src="https://user-images.githubusercontent.com/1234900/36613976-f92caeee-188f-11e8-8d0a-5c681f0706a0.png" width="400">
<img src="https://user-images.githubusercontent.com/1234900/36614562-fedf1dac-1891-11e8-82d9-9727acfa048c.png" width="400">
And for the reposition button, what about a subtle inverted button style?

**Comment by rachteo** [comment]
<img src="https://user-images.githubusercontent.com/1234900/36623406-547b1d3e-18b9-11e8-9b6a-64eae4573cce.png" width="400">

<img src="https://user-images.githubusercontent.com/1234900/36623410-5a6bc2f2-18b9-11e8-9ad2-0c5c0ee9b990.png" width="400">
Place Here button closer to the base of the globe?

**Comment by apike** [comment]
I would say it looks weird for the button to overlap the globe when there's empty space below it - I asked Nigel to try putting it most of the way to the bottom.

**Comment by apike** [comment]
Do we have an asset for this button style in the app? If not, are we sure we want a different style than we use elsewhere, and/or do we want to update/refresh the other buttons to use a new look?

**Comment by rachteo** [comment]
Another alternative would be to keep the button consistent with all the other buttons, especially if we're putting it in the bottom left corner, since it won't pull too much focus there
<img src="https://user-images.githubusercontent.com/1234900/36687160-a16d42c2-1add-11e8-8a6f-48c8af693d7b.png" width="400">

**Comment by apike** [comment]
I think the standard button style on Reposition pulls too much focus for being fairly unimportant - I was more asking about the Place Here style.

**Comment by rachteo** [comment]
<img src="https://user-images.githubusercontent.com/1234900/36688526-9b3921f6-1ae1-11e8-80cd-3ab32aaede06.png" width="400">
Sorry, the rounded corners didn't scale well when I made the button larger. Here's the correctly rounded button that's used for the Traceroute and the Info pages

**Comment by apike** [comment]
Trying to place it immediately at the bottom of the globe is more code, but that seems to be what @rachteo and @nbrooke want to do so I'd be open to seeing it in action. My instinct is that it'll feel better most of the way to the bottom of the screen, but it's hard to tell from a mock.

**Comment by nbrooke** [comment]
Do we actually want it tracking the bottom of the globe, like moving if the globe moves up and down (position is not fixed due to the intersection with the floor). I assume it would just be "near where the bottom of the globe usually is" in which case it's not really any more complicated.

**Comment by apike** [comment]
I'd rather have it cleanly below the globe on all devices, personally.

**Comment by nbrooke** [comment]
This look, with positioning for place here at the bottom of the screen, is implemented in master now.
