### ISSUE TITLE
AR surface search needs message to move camera around

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#534]
If this is a limitation of ARKit, we'll need to copy what other AR apps use to tell users to move the camera to get a fix. If this is fixable, we should fix it.

**Comment by nbrooke** [comment]
Need to pick the exact text for this.

**Comment by apike** [comment]
Let's use "Move the camera across a flat surface to place the map."

**Comment by nbrooke** [comment]
Implemented in master now.
