### ISSUE TITLE
Intro tips don't remember what you've tapped

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#553]
On first installation, we have little "intro" tips that point out the toolbar buttons of the app. They used to remember if you explored them out of order, but they don't seem to in the current build. Steps to repro:

1. Delete and reinstall current master
2. Launch app, notice tip about searching
3. Tap timeline mode, tap a node
4. Tap search to dismiss that tooltip
5. Switch to network to dismiss that tooltip

Expected: App remembers you've seen timeline mode, tips are now complete
Actual: App shows you the timeline mode tip even though you've already tried timeline mode

**Comment by nbrooke** [comment]
Maybe some regression form the change to do smarter positioning of these? Though it seems a little weird that change would break any of the behaviour.

**Comment by robmaceachern** [comment]
The changes for that shouldn't have caused this type of regression but I suppose it's possible https://github.com/steamclock/internetmap/pull/542/files

**Comment by nbrooke** [comment]
Yeah, that's the weird thing about it. That change looks harmless from a behaviour standpoint, but I THINK that's been the only change to anything involving the tooltips, so I' not sure what else would have broken it either.

**Comment by robmaceachern** [comment]
I reverted the changes in #542 and the problem still occurs. I'll see if I can track down where this was introduced.
